name: Build EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pynput pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --hidden-import pynput.keyboard --hidden-import pynput.mouse keyboard_touchpad.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: keyboard_touchpad_exe
        path: dist/keyboard_touchpad.exe
